name: Terraform Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate
